helm:
  parameters:
  - name: image.name
    value: harbor-dev-repo.ops.io/podinfo-sample
    forcestring: true
  - name: image.tag
    value: develop@sha256:32dd6b256bd289accdd18d0519b85857ea96b889d7eb1376db378d804c5d1d19
    forcestring: true
